repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^helm-diff/testdata/chart/templates
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -l -w
        language: system
        types: [go]
      - id: go-vet
        name: go vet
        entry: bash -c 'cd helm-diff && go vet ./...'
        language: system
        types: [go]
        pass_filenames: false
